### PR TITLE
[no merge - updating] Move functions from wiki

### PR DESCRIPTION
**Pull request by iriberri**
I moved all the contents from the Wiki here and deleted all "new" things, which I copied previously to the branch "proposed_georef_functions".

cc @javisantana @rafatower

### CODE REVIEW

**Comment by javisantana** [comment]
are you using code in the database or the wiki one? Yesterday we found some differences

**Comment by iriberri** [comment]
Code in the wiki. Rafa has told me too that there are some functions undocumented in the wiki which are being used.

**Comment by rafatower** [comment]
I would double-check what we add to the repo against production.

E.g from production:
```
Schema              | public
Name                | geocode_admin1_polygons
Result data type    | SETOF geocode_admin_v1
Argument data types | name text[], inputcountry text
Type                | normal
Security            | definer
Volatility          | volatile
Owner               | *****
Language            | plpgsql
Source code         | 
                    |   DECLARE 
                    |     ret geocode_admin_v1%rowtype;
                    |   BEGIN
                    | 
                    |   FOR ret IN WITH 
                    |     p AS (SELECT r.c, r.q, (SELECT iso3 FROM country_decoder WHERE lower(inputcountry) = ANY (synonyms)) i FROM (SELECT  trim(replace(lower(unnest(name)),'.',' ')) c, unnest(name) q) r)
                    |     SELECT
                    |        q, geom, CASE WHEN geom IS NULL THEN FALSE ELSE TRUE END AS success
                    |     FROM (
                    |       SELECT 
                    |         q, (
                    |           SELECT the_geom 
                    |           FROM global_province_polygons
                    |           WHERE p.c = ANY (synonyms) 
                    |           AND iso3 = p.i
                    |           -- To calculate frequency, I simply counted the number of users
                    |           -- we had signed up in each country. Countries with more users, 
                    |           -- we favor higher in the geocoder :)
                    |           ORDER BY frequency DESC LIMIT 1
                    |         ) geom
                    |       FROM p) n
                    |     LOOP
                    |     RETURN NEXT ret;
                    |   END LOOP;
                    |   RETURN;
                    | END
                    | 
Description         | 
```
which does not match with either version (current master nor pull request). I'd put that code in "quarantine".

**Comment by iriberri** [comment]
Ok, let's do something: teach me how to see those functions (in the database of user geocoding user? by using \df?) and I'll contrast and copy all the things in there.

**Comment by rafatower** [comment]
Yeah, using `\df` and `\df+` I'll send you the specifics by mail.

**Pull request closed without merging**
